services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true
    init: true
    ports:
      - "8000:8000"

  db:
    image: postgres:12
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password